# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.locales: 'en|pl'
    app.archiveLimit: 10

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $formLoginAuthenticator: '@security.authenticator.form_login.main'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventSubscriber\LocaleSubscriber:
        arguments:
            $defaultLocale: '%kernel.default_locale%'

    Symfony\Contracts\HttpClient\HttpClientInterface:
        factory: ['App\Factory\HttpClientStaticFactory', 'create']
        arguments: ['%env(ALLOW_PRIVATE_NETWORKS)%']

    App\Service\RequestsRunner:
        bind:
            $client: '@Symfony\Contracts\HttpClient\HttpClientInterface'

when@test:
    parameters:
        app.archiveLimit: 3